.github/workflows/main.yml
README.md

Signed-off-by: danhill <danhill@digital.uc.dwp.gov.uk>

rename the released zip file to match the repo rename

---

common.py
provisioner.py

- Parse envvars correctly
- Update validation schema to match creation schema

Parse envvars correctly; update validation schema

---

create_table.sql

Add a temporary delete to flush bad data

Add a temporary delete to flush bad data

---

create_table.sql
provisioner.py

Temporary cleanup delete statement

Temporary cleanup delete statement

---

provisioner.py

remove bad statement

---

provisioner.py

Reverts dwp/dataworks-ingestion-metadata-interface#15

Revert "delete_temporary_bad_data"

---

provisioner.py

Remove data from equalities and ucfs metadata store table so that they are nuked and we can review them clean due to other fixes that have already gone in

Readd delete equalities and ucfs

---

provisioner.py

Reverts dwp/dataworks-ingestion-metadata-interface#19

Revert "Readd delete equalities and ucfs"

---

provisioner.py

Reverts dwp/dataworks-ingestion-metadata-interface#21

Revert "Drop table for metadata store tables to circumvent transaction timeout"

---

provisioner.py

Change validation method to use the new column type

Change validation method to use the new column type

---

provisioner.py

The valid type when searching is big int 20

The valid type when searching is big int 20

---

.github/workflows/main.yml
src/common/database.py

Update workflow for the new file structure

Update workflow for the new file structure

---

.github/workflows/main.yml

Create the common directory

---

.github/workflows/main.yml

There are more sub directories so create those as well

There are more sub directories so create those as well

---

src/provisioner_lambda/provisioner.py
src/query_lambda/query.py
tests/test_query.py

Fix var name clash, update LIKE statements to have wildcards

Fix var name clash, update LIKE statements to have wildcards

---

src/common/database.py
src/provisioner_lambda/provisioner.py

Remove the drop table and add SQL logging

Remove the drop table and add SQL logging

---

src/common/database.py

Remove broken log

---

src/unreconciled_lambda/unreconciled.py
tests/test_database.py

Fix the tests and styling for flake8

Fix the tests and styling for flake8

---

README.md

Added to readme about what the unreconciled lambda is for

Update Readme for unreconciled lambda

---

README.md
src/common/common.py
src/provisioner_lambda/provisioner.py
src/query_lambda/query.py
src/unreconciled_lambda/unreconciled.py

Missed this which would prevent us doing metrics for the individual tables.

Added table name to log for queries

---

src/common/database.py

Add audit table
